accounts: []
deployments:
  - name: kergiva-org-web
    replicas: ${replicas}
    image:
      repo: ${image_repo}/${image_name}
      tag: ${image_tag}
      pull_policy: Always
      pull_secret: ${image_pull_secret}
    security:
      read_only_root_filesystem: true
      run_as_non_root: true
      run_as_user: "1000"
      run_as_group: "1000"
      drop_all_capabilities: true
      pod_fs_group: "1000"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    probes:
      liveness:
        path: /
        port: "80"
      readiness:
        path: /
        port: "80"
    init_containers:
      - name: install
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/cache/nginx && chown 1000:1000 /var/cache/nginx']
        volumeMounts:
          - mountPath: /var/cache
            name: cache-volume
    environment_variables:
      NGINX_PORT: "80"
    volume_mounts:
      site-config: /etc/nginx/conf.d/
      cache-volume: /var/cache
      run-volume: /var/run
    endpoints:
      - name: ${service_name}
        container_port: ${service_port}
        protocol: ${service_protocol}
volumes:
  - name: nginx-config
    configMap:
      name: kergiva-org-web-site-configmap
  - name: site-config
    configMap:
      name: kergiva-org-web-site-configmap
  - name: cache-volume
    emptyDir: {}
  - name: run-volume
    emptyDir: {}
  - name: database-config
    configMap:
      name: kergiva-org-web-database-configmap
nodeSelector: {}
tolerations: []
affinity: {}